version: '3'
services:
  web:
    image: takapon564/rest-web
    #  build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 80:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: takapon564/my-db
    # image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
volumes:
  db-volume:
  